# Site settings
title: David Andersson
description: 'This is the personal page of David Andersson, Security Architect. This is my online resume and I will occasionally write about topics that interest me.' # this means to ignore newlines until "baseurl:"
permalink: ':title:output_ext'
baseurl: "/davidandersson_se" # the subpath of your site, e.g. /blog
url: "https://davand01.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/img/branding/header-image-black-text.png"
logo-icon: "/assets/img/branding/logo.svg"
logo-icon-SEO: "/assets/img/branding/logo.svg" # must be a non SVG file

# Night/Dark mode
# Default mode is "auto", "auto" is for auto nightshift
# (19:00 - 07:00), "manual" is for manual toggle, and
# "on/off" is for default on/off.
#
# Whatever the user's choice is, it will supersede the
# default setting of the site and be kept during the
# visit (session). Only the dark mode setting is "manual",
# it will be always kept on every visit (i.e. no matter
# the browser is closed or not)
night_mode: "auto"

logo-dark: "/assets/img/branding/header-image-white-text.png"
highlight_theme: syntax-base16.monokai.dark # select a dark theme for the code highlighter if needed

# Author settings
author: David Andersson # add your name
about-author: "<span style=\"display: block; text-align: center;\">Engineering leader, information security architect <br />20 years experience within the field </span><br /><span style=\"display: block; text-align: justify; font-size: 60%;\"> Business aligned IT and information security expert with both passion and talent for designing and implementing security architecture and governance that build security awareness across the organization. Creates and implements solutions that align with security standards and operational goals.<br />I will post blogs about things that interest me in the area of Information Security here<br /><br />⫸ Key skills: Application Security Programs, Information Security Management Systems, Risk Management, Cloud Security, Security Architecture, Security Management<br />⫸ CISSP, CISM, SCF, ISO 27001 LI</span>" 
author-pic: david.jpg

# Contact links
email: info@davidandersson.se # Add your Email address
phone: # Add your Phone number
website: https://davand01.github.io # Add your website
linkedin: ictsec # Add your Linkedin handle
github: davand01 # Add your Github handle
twitter: '' # Add your Twitter handle
bandcamp:  # Add your Bandcamp username
stackoverflow:  # Add your stackoverflow account

# Newsletter
#mailchimp: ""

# Tracker
#analytics: 
#fbadmin: 

# Paginate
paginate: 6
paginate_path: 'page:num'
words_per_minute: 200

extensions:
  mermaid_enable: true

# Comments
comments: #utteranc  #[disqus, utteranc]
comments_opts:
  comments_curtain: yes # leave empty to show the disqus embed directly
  repo: # The GitHub repo URL.  https://utteranc.es/
  issue_term: # The GitHub issue label
  label: # The GitHub comments label
  theme: # The GitHub comment's there. e.g. github-dark
  # Disqus
  discus_identifier: # Add your discus identifier

# Build settings
markdown: kramdown
mathjax: true
highlighter: rouge
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Outputting
timezone: "Europe/Stockholm" # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

category_archive:
  type: liquid
  path: /categories/

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]